// ============================================================================
//  fsw/apps/ttc/ttc_app.hpp -- the telemetry, tracking and command application.
//
//  This is the spacecraft's mouth and ears. It owns:
//
//    * the uplink path: bytes from the link, reassembled into Space Packets,
//      validated, dispatched to a PUS service handler, answered with ST[01]
//      verification reports
//    * the downlink path: periodic housekeeping, event reports, and the
//      responses generated by services
//
//  It deliberately knows nothing about attitude or power. Those subsystems
//  publish their housekeeping on the software bus; this application caches
//  whatever last arrived and reports it. Adding a subsystem therefore requires
//  no change here at all -- only a new entry in the dictionary.
//
//  BUFFER OWNERSHIP. Every buffer is a fixed-size member of this class. No
//  allocation, no shared scratch space, and the worst-case memory footprint of
//  the whole communications stack is `sizeof(TtcApp)`, visible at compile time.
// ============================================================================
#pragma once

#include <cstddef>
#include <cstdint>

#include "apps/ttc/pus.hpp"
#include "apps/ttc/space_packet.hpp"
#include "core/bus.hpp"
#include "core/event_log.hpp"
#include "core/param_store.hpp"
#include "core/scheduler.hpp"
#include "core/static_vector.hpp"
#include "generated/commands.hpp"
#include "generated/dictionary.hpp"
#include "generated/telemetry.hpp"
#include "hal/clock.hpp"
#include "hal/link.hpp"

namespace fsw::ttc {

class TtcApp {
 public:
    // Sized for the worst case: the largest packet the dictionary can produce,
    // several times over, so a burst of uplink during one tick cannot be lost
    // merely because the application had not run yet.
    static constexpr size_t kRxBufferBytes = 4096;
    static constexpr size_t kTxScratchBytes = kMaxPacketBytes;

    TtcApp(hal::ILink& link, hal::IClock& clock, core::Bus& bus,
           core::EventLog& events, core::ParamStore& params,
           const core::Scheduler& scheduler);

    // Wire up bus subscriptions and the event sink. Called once at startup,
    // before the scheduler starts.
    core::Status init();

    // ---- scheduler entry points ----------------------------------------
    // Registered at different rates in main.cpp. Static thunks are used
    // because the scheduler takes a plain function pointer; each simply
    // recovers `this` from the context pointer.

    // 50 Hz: pump the link, reassemble and dispatch anything that arrived.
    // Runs fast because command latency is the thing operators feel most.
    static void task_receive(void* context);

    // 10 Hz: evaluate which housekeeping structures are due and emit them.
    static void task_telemetry(void* context);

    // ---- statistics, reported in SYS_HK --------------------------------
    uint32_t tc_received() const { return tc_received_; }
    uint32_t tc_rejected() const { return tc_rejected_; }
    uint32_t tm_sent()     const { return tm_sent_; }
    bool     link_up()     const { return link_.connected(); }

    // Exposed so the mode manager can be told about a ground request without
    // TtcApp needing to know the mode manager exists.
    void set_mode_request_topic(core::Topic topic) { mode_topic_ = topic; }

 private:
    // ---- uplink --------------------------------------------------------
    void pump_link();
    void drain_rx_buffer();
    void handle_tc(const ReceivedTc& tc);

    // Individual PUS service handlers. Each returns the failure code to be
    // reported in ST[1,8], or Ok on success.
    core::FailureCode svc_test(const ReceivedTc& tc);
    core::FailureCode svc_housekeeping(const ReceivedTc& tc);
    core::FailureCode svc_parameter(const ReceivedTc& tc);
    core::FailureCode svc_function(const ReceivedTc& tc);

    // ---- downlink ------------------------------------------------------
    bool send_packet(size_t length);
    void send_verification(const ReceivedTc& tc, uint8_t subtype,
                           core::FailureCode failure);
    void send_hk(dict::HkSid sid);
    void send_param_report(dict::ParamId id, double value);
    void send_test_report();

    // Event sink, installed into the EventLog so every raised event is
    // downlinked as ST[05] the moment it happens.
    static void event_sink(void* context, const core::EventRecord& record);
    static double mission_time(void* context);

    // Bus handlers caching subsystem housekeeping for later reporting.
    static void on_adcs_hk(void* context, core::Topic topic,
                           const uint8_t* data, size_t length);
    static void on_eps_hk(void* context, core::Topic topic,
                          const uint8_t* data, size_t length);

    // Message type counter, kept per (service, subtype) as PUS requires, so
    // the ground can detect a lost report of one specific kind rather than
    // only a gap in the overall packet stream.
    uint16_t next_message_count(uint8_t service, uint8_t subtype);

    core::CucTime now_cuc() { return core::CucTime::from_seconds(clock_.mission_time_s()); }

    hal::ILink&            link_;
    hal::IClock&           clock_;
    core::Bus&             bus_;
    core::EventLog&        events_;
    core::ParamStore&      params_;
    const core::Scheduler& scheduler_;

    SequenceCounter seq_ttc_;
    SequenceCounter seq_adcs_;
    SequenceCounter seq_eps_;

    uint8_t rx_buffer_[kRxBufferBytes]{};
    size_t  rx_used_ = 0;
    uint8_t tx_scratch_[kTxScratchBytes]{};

    // Which housekeeping structures are being generated, and when each is next
    // due. Indexed by position in the generated dictionary, not by SID value.
    struct HkState {
        dict::HkSid sid;
        bool        enabled  = true;
        double      next_due = 0.0;   // mission time, seconds
    };
    core::StaticVector<HkState, dict::kHkStructureCount> hk_;

    // Latest housekeeping published by other applications. Zero-initialised,
    // so before ADCS exists the ground sees a well-formed packet full of
    // zeroes rather than nothing at all -- which is the correct behaviour: the
    // packet's presence proves the telemetry chain works.
    tlm::AdcsHk adcs_hk_{};
    tlm::EpsHk  eps_hk_{};

    struct MsgCounter { uint8_t service; uint8_t subtype; uint16_t count; };
    core::StaticVector<MsgCounter, 32> msg_counters_;

    core::Topic mode_topic_ = core::Topic::ModeRequest;

    uint32_t tc_received_ = 0;
    uint32_t tc_rejected_ = 0;
    uint32_t tm_sent_     = 0;
    bool     was_connected_ = false;
};

}  // namespace fsw::ttc
